# اسم workflow که توی تب Actions می‌بینی
name: "اولین جریان کاری من"
# این workflow قراره با چه اتفاقی اجرا بشه؟ اینجا می‌گیم با هر بار push کردن کد
on: [push]

# کارهایی که باید انجام بشن
jobs:
  # اسم این کار (میتونه هرچیزی باشه)
  say-hello:
    # این کار روی یه ماشین مجازی لینوکس اجرا می‌شه
    runs-on: ubuntu-latest
    # مرحله‌هایی که باید انجام بشن
    steps:
      # این یه مرحله‌ست که یه دستور ساده رو اجرا می‌کنه
      - name: سلام دنیا!
        run: echo "سلام! این اولین workflow من در گیت‌هاب اکشن هستم."
